const STORAGE_KEY = "klascode.demo.v2";
const ALL_BLOCKS = Object.keys(window.KlasCodeEditor?.BLOCKS||{});
const seeded = {
  activity:"Micro:bit Magic", roomName:"Groep 7 · Maaklab", joinCode:"BLOEM-ROBOT-PAARS", pin:"482 193",
  paused:false, activeTab:"dashboard", selectedStudent:"s1", enabledBlocks:ALL_BLOCKS,
  students:[
    {id:"s1",name:"Noor",status:"In de klas",feeling:"",lastSeen:"Net actief",workspace:null,incomingWorkspace:null},
    {id:"s2",name:"Milan",status:"In de klas",feeling:"",lastSeen:"Net actief",workspace:null,incomingWorkspace:null},
    {id:"s3",name:"Sofia",status:"Klaar",feeling:"🙂",lastSeen:"1 min geleden",workspace:null,incomingWorkspace:null},
    {id:"s4",name:"Daan",status:"Offline",feeling:"",lastSeen:"3 min geleden",workspace:null,incomingWorkspace:null},
    {id:"s5",name:"Lina",status:"In de klas",feeling:"",lastSeen:"Net actief",workspace:null,incomingWorkspace:null}
  ],
  startedAt:new Date().toISOString(), starterWorkspace:null, version:2
};
let state=loadState(), toastTimer, editorController=null, activeContext=null;
const app=document.querySelector("#app"), toastNode=document.querySelector("#toast");

function loadState(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));return saved?{...structuredClone(seeded),...saved}:structuredClone(seeded);}catch{return structuredClone(seeded);}}
function persist(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
function esc(value=""){return String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function initials(name){return name.trim().split(/\s+/).map(s=>s[0]).join("").slice(0,2).toUpperCase();}
function notify(message){toastNode.textContent=message;toastNode.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>toastNode.classList.remove("show"),2600);}
function statusClass(s){return s==="Offline"?"offline":s==="Klaar"?"finished":state.paused?"paused":"";}
function selected(){return state.students.find(s=>s.id===state.selectedStudent)||state.students[0];}
function saveAndRender(){persist();render();}
function heading(kicker,title,sub){return `<div class="toolbar"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1><p class="subtitle">${sub}</p></div><div class="spacer"></div><button class="button secondary" data-action="save-session">Bewaar klas</button></div>`;}
function nav(){const tabs=[["dashboard","Klasoverzicht"],["code","Leerlingcode"],["editor","Startcode"],["blocks","Blokken kiezen"]];return `<nav class="tabs" aria-label="Klasnavigatie">${tabs.map(([id,label])=>`<button class="tab" data-tab="${id}" aria-selected="${state.activeTab===id}">${label}</button>`).join("")}</nav>`;}
function studentRows(){if(!state.students.length)return `<div class="empty">Er zijn nog geen leerlingen. Deel de klascode om te beginnen.</div>`;return `<div class="student-list">${state.students.map(s=>`<div class="student ${s.id===state.selectedStudent?"selected":""}" data-select="${s.id}"><input type="checkbox" aria-label="Selecteer ${esc(s.name)}" data-check="${s.id}" ${s.id===state.selectedStudent?"checked":""}><div class="student-main"><div class="avatar">${esc(initials(s.name))}</div><div><div class="student-name">${esc(s.name)}</div><div class="student-meta">${esc(s.lastSeen)}${s.feeling?` · Gevoel: ${esc(s.feeling)}`:""}</div></div></div><span class="status ${statusClass(s.status)}">${state.paused&&s.status!=="Offline"?"Gepauzeerd":esc(s.status)}</span><button class="icon-button" data-action="edit-student" data-id="${s.id}" aria-label="Bewerk ${esc(s.name)}">⋯</button></div>`).join("")}</div>`;}
function dashboard(){const active=state.students.filter(s=>s.status!=="Offline").length,finished=state.students.filter(s=>s.status==="Klaar").length;return `${heading("DOCENT · LIVE KLAS",state.activity,"Volg het werk van je leerlingen en help wanneer dat nodig is.")}${nav()}<div class="layout"><section class="stack"><article class="card"><div class="card-heading"><div><h2>Leerlingen</h2><p class="subtitle">${active} actief · ${finished} klaar</p></div><div class="actions"><button class="button secondary small" data-action="pause">${state.paused?"Hervat klas":"Pauzeer klas"}</button><button class="button small" data-tab="editor">Maak startcode</button></div></div><div class="stats"><div class="stat"><strong>${state.students.length}</strong><span>Leerlingen</span></div><div class="stat"><strong>${active}</strong><span>In de klas</span></div><div class="stat"><strong>${finished}</strong><span>Hebben afgerond</span></div></div>${studentRows()}<div class="notice-line">Selecteer een leerling om de blokken te bekijken of samen aan te passen.</div></article><article class="card"><h2>Klasgegevens</h2><div class="notice"><span>●</span><div><strong>${state.paused?"De klas is gepauzeerd.":"De klas is open."}</strong><br>${state.paused?"Leerlingen kunnen tijdelijk niet verder werken.":"Leerlingen kunnen met de blokken aan de slag."}</div></div><div class="invite-box"><div class="invite-value"><span>Klascode</span><strong class="join-code">${esc(state.joinCode)}</strong></div><div class="invite-value"><span>Toegangscode</span><strong class="pin">${esc(state.pin)}</strong></div></div></article></section><aside class="stack"><article class="card"><h2>Leerling uitnodigen</h2><p class="subtitle">Deel de link met je klas.</p><div class="field"><label for="join-link">Deellink</label><input id="join-link" readonly value="${esc(location.origin+location.pathname)}?join=${esc(state.joinCode)}"></div><div class="actions"><button class="button secondary" data-action="copy-link">Kopieer link</button><button class="button secondary" data-action="copy-code">Kopieer klascode</button></div><p class="notice-line">Demo: leerling- en docenttabbladen synchroniseren via browseropslag op hetzelfde apparaat.</p></article><article class="card"><h2>Bewaren en terugkijken</h2><div class="stack"><button class="button secondary" data-action="save-session">Download klasbestand</button><button class="button secondary" data-action="restore">Open klasbestand</button><button class="button secondary" data-action="report">Download voortgangsrapport</button><button class="button danger" data-action="end-session">Beëindig deze klas</button></div></article></aside></div>`;}

function microbitPreview(){return `<div class="microbit-card"><div class="microbit-board"><div class="microbit-top"><span class="microbit-mark">micro:bit</span><span class="microbit-model">BBC · <select id="microbit-version" class="microbit-version" aria-label="Kies micro:bit versie"><option value="v2">V2</option><option value="v1">V1</option></select></span></div><div class="microbit-touch" aria-hidden="true"><span></span><span></span><span></span></div><div id="microbit-preview" class="led-matrix" role="img" aria-label="Micro:bit LED-scherm">${Array.from({length:25},(_,i)=>`<span class="led-dot" data-led="${i}"></span>`).join("")}</div><div class="microbit-controls"><button class="microbit-button" data-microbit-button="A" aria-label="Druk op knop A">A</button><span class="microbit-speaker" aria-label="Luidspreker">◖))</span><button class="microbit-button" data-microbit-button="B" aria-label="Druk op knop B">B</button></div><div class="microbit-connector" aria-hidden="true"><span></span><span></span><span></span><span></span><span></span></div></div><p class="microbit-label">Klik op A of B om je programma te testen.</p><p id="sound-note" class="microbit-label" aria-live="polite"></p></div>`;}
function ideMarkup({title,help}){return `<div class="card-heading"><div><h2>${title}</h2><p class="subtitle">${help}</p></div></div><div class="ide-controls"><button id="run-program" class="button">▶ Start opnieuw</button><button id="stop-program" class="button secondary" disabled>■ Stop</button><button id="clear-workspace" class="button secondary">Wis werkruimte</button><span class="spacer"></span><div class="mode-switch" role="group" aria-label="Weergave kiezen"><button id="show-blocks" class="button secondary" aria-pressed="true">Blokken</button><button id="show-javascript" class="button secondary" aria-pressed="false">JavaScript</button></div><button id="download-code" class="button secondary">Download code</button></div><div class="ide-layout" style="margin-top:14px"><div class="ide-main"><div id="blocks-mode"><div id="blockly-workspace" class="ide-workspace" aria-label="Blokkenwerkruimte">Blokkeneditor laden…</div></div><section id="javascript-mode" class="javascript-editor" hidden aria-label="JavaScript-code"><pre id="generated-code">// Sleep blokken in de werkruimte.</pre><p>JavaScript wordt automatisch opgebouwd vanuit je blokken.</p></section></div><aside class="ide-side">${microbitPreview()}<p class="ide-footnote">De simulator start vanzelf en wordt opnieuw uitgevoerd als je blokken aanpast. De code kan in deze versie worden bekeken en gedownload.</p></aside></div>`;}

function codeTab(){const s=selected();if(!s)return `${heading("DOCENT","Leerlingcode","Selecteer een leerling in het klasoverzicht.")}${nav()}<div class="empty">Er zijn nog geen leerlingen.</div>`;return `${heading("DOCENT · LEERLINGWERK",esc(s.name),`Laatste activiteit: ${esc(s.lastSeen)}${s.feeling?` · Gevoel: ${esc(s.feeling)}`:""}`)}${nav()}<div class="layout"><section class="card">${ideMarkup({title:`Werkruimte van ${esc(s.name)}`,help:"Bekijk en pas de blokken samen aan."})}<div class="actions" style="margin-top:14px"><button class="button" data-action="share-to-student" data-id="${s.id}">Deel aangepaste code</button><button class="button secondary" data-action="mark-progress" data-id="${s.id}">Zet op ‘In de klas’</button><button class="button secondary" data-action="mark-finished" data-id="${s.id}">Zet op ‘Klaar’</button><button class="button danger" data-action="remove-student" data-id="${s.id}">Verwijder leerling</button></div></section><aside class="card"><h2>Deel code met leerlingen</h2><p class="subtitle">De leerling krijgt eerst de vraag om de nieuwe code te openen.</p><div class="student-list" style="margin:14px 0">${state.students.map(x=>`<label class="student"><input type="checkbox" data-send-select="${x.id}" ${x.id===s.id?"checked":""}><span class="student-name">${esc(x.name)}</span><span class="status ${statusClass(x.status)}">${esc(x.status)}</span></label>`).join("")}</div><button class="button" data-action="share-selected">Deel met geselecteerden</button></aside></div>`;}
function editorTab(){return `${heading("DOCENT · STARTCODE","Maak je startprogramma","Kies de blokken die passen bij de les en test het programma in de preview.")}${nav()}<section class="card">${ideMarkup({title:"Startcode voor de klas",help:"Sleep de gekleurde blokken naar de werkruimte."})}<div class="field" style="margin-top:16px"><label for="activity-instructions">Uitleg voor leerlingen</label><textarea id="activity-instructions">${esc(state.instructions||"Probeer de muziekblokken uit. Wat hoor je als je op knop A drukt?")}</textarea></div><div class="actions"><button class="button" data-action="save-instructions">Bewaar uitleg</button><button class="button teal" data-action="share-all">Deel startcode met alle leerlingen</button></div></section>`;}
function blocksTab(){const descriptions={kc_on_button:"Reageer op knop A of B",kc_forever:"Herhaal zolang het programma loopt",kc_show_icon:"Toon een pictogram op de leds",kc_show_number:"Toon een getal",kc_clear_leds:"Wis het ledscherm",kc_play_melody:"Speel een ingebouwde melodie",kc_play_note:"Speel een losse noot",kc_set_volume:"Regel het volume",kc_pause:"Wacht een aantal milliseconden",kc_repeat:"Herhaal blokken een vast aantal keer"};const labels={kc_on_start:"Bij de start",kc_on_button:"Als knop wordt ingedrukt",kc_forever:"Blijf herhalen",kc_show_icon:"Toon pictogram",kc_show_number:"Toon getal",kc_clear_leds:"Wis ledscherm",kc_play_melody:"Speel melodie",kc_play_note:"Speel noot",kc_set_volume:"Stel volume in",kc_pause:"Wacht",kc_repeat:"Herhaal"};return `${heading("DOCENT · BLOKKENSET","Kies de blokken voor deze klas","Zet alleen de blokken klaar die leerlingen in deze opdracht nodig hebben.")}${nav()}<section class="card"><div class="notice"><span>i</span><div><strong>‘Bij de start’ staat altijd aan.</strong><br>Andere gebeurtenisblokken kun je per les aan- of uitzetten.</div></div><div class="config-grid" style="margin:16px 0">${ALL_BLOCKS.filter(type=>type!=="kc_on_start").map(type=>`<label class="block-toggle"><input type="checkbox" data-block-config="${type}" ${state.enabledBlocks.includes(type)?"checked":""}><span><strong>${labels[type]||window.KlasCodeEditor.BLOCKS[type]?.label||type}</strong><small>${descriptions[type]||"Blok voor de micro:bit"}</small></span></label>`).join("")}</div><button class="button" data-action="save-block-config">Bewaar blokken voor deze klas</button></section>`;}
function joinView(){return `<div class="student-view">${heading("LEERLING","Doe mee met de klas","Vul je naam in om te beginnen.")}<article class="card"><div class="field"><label for="student-name-input">Jouw naam</label><input id="student-name-input" autocomplete="given-name" maxlength="40" placeholder="Bijvoorbeeld Sam"></div><button class="button" data-action="join-class">Ga naar de klas</button><p class="help" style="margin-top:14px">Klascode: <strong>${esc(state.joinCode)}</strong></p></article></div>`;}
function studentWorkspace(){const id=sessionStorage.getItem("klascode.student"),s=state.students.find(x=>x.id===id)||selected();return `<div class="student-view">${heading(`LEERLING · ${esc(s?.name||"")}`,state.activity,"Bouw je programma met de blokken en test het hier.")}<article class="card"><div class="card-heading"><div><h2>Jouw programma</h2><p class="subtitle">${state.paused?"De docent heeft de klas tijdelijk gepauzeerd.":"Druk op Start programma en probeer daarna knop A of B."}</p></div><span class="status ${state.paused?"paused":""}">${state.paused?"Gepauzeerd":"In de klas"}</span></div>${ideMarkup({title:"Blokken en micro:bit-preview",help:"Sleep blokken, start je programma en test de knoppen."})}<div class="actions" style="margin-top:16px"><button class="button" data-action="finish">Ik ben klaar</button><button class="button secondary" data-action="leave">Verlaat de klas</button></div></article></div>`;}

function mountEditor(){if(editorController){editorController.dispose();editorController=null;}const workspace=document.querySelector("#blockly-workspace");if(!workspace)return;const studentId=sessionStorage.getItem("klascode.student");if(studentId)activeContext={kind:"learner",id:studentId};else if(state.activeTab==="code")activeContext={kind:"review",id:state.selectedStudent};else activeContext={kind:"starter"};const student=activeContext.id&&state.students.find(s=>s.id===activeContext.id);const initial=activeContext.kind==="starter"?state.starterWorkspace:student?.workspace||state.starterWorkspace;editorController=window.KlasCodeEditor?.mount({workspaceId:"blockly-workspace",previewId:"microbit-preview",codeId:"generated-code",saveKey:`${STORAGE_KEY}.${activeContext.kind}.${activeContext.id||""}`,initialState:initial,blockConfig:state.enabledBlocks,paused:state.paused,onChange:snapshot=>{if(activeContext.kind==="starter")state.starterWorkspace=snapshot;else state.students=state.students.map(s=>s.id===activeContext.id?{...s,workspace:snapshot,lastSeen:"Net opgeslagen",status:state.paused?"Gepauzeerd":"In de klas"}:s);persist();}})||null;}
function render(){if(editorController){editorController.dispose();editorController=null;}const params=new URLSearchParams(location.search);if(params.has("join")&&!sessionStorage.getItem("klascode.student")){app.innerHTML=joinView();renderPauseOverlay();return;}if(sessionStorage.getItem("klascode.student"))app.innerHTML=studentWorkspace();else app.innerHTML=state.activeTab==="code"?codeTab():state.activeTab==="editor"?editorTab():state.activeTab==="blocks"?blocksTab():dashboard();mountEditor();const id=sessionStorage.getItem("klascode.student"),incoming=id&&state.students.find(s=>s.id===id)?.incomingWorkspace;if(incoming)setTimeout(()=>showSharedWorkspacePrompt(id,incoming),0);renderPauseOverlay();}

function renderPauseOverlay(){document.querySelector("#class-pause-overlay")?.remove();document.body.classList.toggle("is-paused",state.paused);app.inert=state.paused;if(!state.paused)return;editorController?.stop?.();const isStudent=!!sessionStorage.getItem("klascode.student");const overlay=document.createElement("div");overlay.id="class-pause-overlay";overlay.className="class-pause-overlay";overlay.setAttribute("role","alertdialog");overlay.setAttribute("aria-modal","true");overlay.setAttribute("aria-labelledby","pause-title");overlay.innerHTML=`<section class="pause-message"><div class="pause-symbol" aria-hidden="true">Ⅱ</div><p class="eyebrow">${isStudent?"LESTIJD":"DOCENTENBEDIENING"}</p><h1 id="pause-title">${isStudent?"De les is gepauzeerd":"De klas is gepauzeerd"}</h1><p>${isStudent?"Je kunt verder zodra je docent de les hervat.":"Leerlingen kunnen niets bedienen. Hervat de les om verder te gaan."}</p>${isStudent?"":"<button class=\"button\" data-resume-class>Hervat de les</button>"}</section>`;document.body.append(overlay);overlay.querySelector("[data-resume-class]")?.addEventListener("click",()=>{state.paused=false;saveAndRender();notify("De les is hervat.");});}

function download(name,content,type="application/json"){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function selectIds(attr){return [...document.querySelectorAll(`[${attr}]:checked`)].map(el=>el.getAttribute(attr));}
function share(ids){if(!ids.length){notify("Selecteer eerst een leerling.");return;}const snapshot=editorController?.getState();if(!snapshot){notify("Maak eerst een programma met blokken.");return;}state.students=state.students.map(s=>ids.includes(s.id)?{...s,incomingWorkspace:snapshot,lastSeen:"Nieuwe code klaar"}:s);persist();notify(`Startprogramma gedeeld met ${ids.length} leerling${ids.length===1?"":"en"}.`);}
function showSharedWorkspacePrompt(studentId,workspace){if(document.querySelector("[data-share-prompt]"))return;const wrap=document.createElement("div");wrap.className="modal-backdrop";wrap.dataset.sharePrompt="true";wrap.innerHTML=`<section class="modal" role="dialog" aria-modal="true" aria-labelledby="shared-title"><h2 id="shared-title">Je docent deelt nieuwe blokken</h2><p class="subtitle">Open de startcode om die in je werkruimte te zetten. Je huidige blokken worden vervangen.</p><div class="modal-actions"><button class="button secondary" data-decline>Nu niet</button><button class="button" data-accept>Open startcode</button></div></section>`;document.body.append(wrap);wrap.addEventListener("click",event=>{if(event.target===wrap||event.target.closest("[data-decline]")){state.students=state.students.map(s=>s.id===studentId?{...s,incomingWorkspace:null}:s);persist();wrap.remove();return;}if(event.target.closest("[data-accept]")){state.students=state.students.map(s=>s.id===studentId?{...s,workspace,incomingWorkspace:null,lastSeen:"Net actief",status:"In de klas"}:s);persist();wrap.remove();render();notify("De startblokken staan klaar.");}});}
function report(){const rows=state.students.map(s=>`<tr><td>${esc(s.name)}</td><td>${esc(s.status)}</td><td>${esc(s.lastSeen)}</td><td>${esc(s.feeling||"—")}</td></tr>`).join("");const html=`<!doctype html><html><head><meta charset="utf-8"><title>${esc(state.activity)} · Voortgang</title><style>body{font:14px Arial;color:#261f2c}h1{color:#4c325b}table{border-collapse:collapse;width:100%}th,td{border:1px solid #ddd;padding:8px;text-align:left}th{background:#f7f6f9}</style></head><body><h1>${esc(state.activity)} · Voortgang</h1><p>3Dindeklas · ${new Date().toLocaleDateString("nl-NL")}</p><table><thead><tr><th>Leerling</th><th>Status</th><th>Laatst actief</th><th>Gevoel</th></tr></thead><tbody>${rows}</tbody></table></body></html>`;download(`KlasCode-rapport-${new Date().toISOString().slice(0,10)}.doc`,html,"application/msword");}

window.addEventListener("storage",event=>{if(event.key!==STORAGE_KEY)return;const id=sessionStorage.getItem("klascode.student");state=loadState();if(id){const student=state.students.find(s=>s.id===id);if(student?.incomingWorkspace)showSharedWorkspacePrompt(id,student.incomingWorkspace);const status=document.querySelector(".student-view .status");if(status){status.textContent=state.paused?"Gepauzeerd":"In de klas";status.className=`status ${state.paused?"paused":""}`;}renderPauseOverlay();if(state.paused)editorController?.stop?.();else editorController?.run?.();return;}render();});
app.addEventListener("click",async event=>{const tab=event.target.closest("[data-tab]");if(tab){if(tab.dataset.tab==="code"&&!state.selectedStudent&&state.students[0])state.selectedStudent=state.students[0].id;state.activeTab=tab.dataset.tab;saveAndRender();return;}const row=event.target.closest("[data-select]");if(row&&!event.target.matches("input,button")){state.selectedStudent=row.dataset.select;state.activeTab="code";saveAndRender();return;}const button=event.target.closest("[data-action]");if(!button)return;const id=button.dataset.id;switch(button.dataset.action){
 case "pause":state.paused=!state.paused;saveAndRender();notify(state.paused?"De klas is gepauzeerd.":"De klas is hervat.");break;
 case "save-session":download(`KlasCode-${state.activity.replace(/[^a-z0-9]+/gi,"-")}.json`,JSON.stringify(state,null,2));notify("Je klasbestand is gedownload.");break;
 case "restore":document.querySelector("#restore-file").click();break;
 case "report":report();break;
 case "end-session":if(confirm("Beëindig je deze klas? Je kunt eerst een klasbestand downloaden.")){download(`KlasCode-${state.activity}.json`,JSON.stringify(state,null,2));state=structuredClone(seeded);saveAndRender();notify("De klas is beëindigd.");}break;
 case "copy-link":try{await navigator.clipboard.writeText(document.querySelector("#join-link")?.value||location.href);notify("De deellink is gekopieerd.");}catch{notify("Kopieer de link uit het veld.");}break;
 case "copy-code":try{await navigator.clipboard.writeText(state.joinCode);notify("De klascode is gekopieerd.");}catch{notify(`Klascode: ${state.joinCode}`);}break;
 case "share-all":share(state.students.map(s=>s.id));break;
 case "share-selected":share(selectIds("data-send-select"));break;
 case "share-to-student":share([id]);break;
 case "mark-progress":state.students=state.students.map(s=>s.id===id?{...s,status:"In de klas"}:s);saveAndRender();notify("Status aangepast.");break;
 case "mark-finished":state.students=state.students.map(s=>s.id===id?{...s,status:"Klaar"}:s);saveAndRender();notify("Status aangepast.");break;
 case "remove-student":if(confirm("Deze leerling uit de klas verwijderen?")){state.students=state.students.filter(s=>s.id!==id);state.selectedStudent=state.students[0]?.id||null;saveAndRender();notify("Leerling verwijderd.");}break;
 case "edit-student":{const s=state.students.find(x=>x.id===id),name=prompt("Pas de naam aan",s?.name||"");if(name?.trim()){state.students=state.students.map(x=>x.id===id?{...x,name:name.trim()}:x);saveAndRender();notify("Naam aangepast.");}break;}
 case "join-class":{if(state.paused){notify("De docent heeft de klas gepauzeerd.");return;}const name=document.querySelector("#student-name-input").value.trim();if(!name){notify("Vul eerst je naam in.");return;}let s=state.students.find(x=>x.name.toLowerCase()===name.toLowerCase());if(!s){s={id:crypto.randomUUID(),name,status:"In de klas",feeling:"",lastSeen:"Net actief",workspace:state.starterWorkspace,incomingWorkspace:null};state.students=[...state.students,s];}else s.status="In de klas";persist();sessionStorage.setItem("klascode.student",s.id);history.replaceState({},"",location.pathname);render();break;}
 case "finish":showFinishDialog();break;
 case "leave":sessionStorage.removeItem("klascode.student");render();break;
 case "save-instructions":state.instructions=document.querySelector("#activity-instructions").value;persist();notify("Uitleg bewaard.");break;
 case "save-block-config":state.enabledBlocks=["kc_on_start",...selectIds("data-block-config")];saveAndRender();notify("Blokkenlijst voor deze klas bewaard.");break;
 }});

document.querySelector("#restore-file").addEventListener("change",async e=>{const file=e.target.files[0];if(!file)return;try{const loaded=JSON.parse(await file.text());if(!Array.isArray(loaded.students))throw new Error("Invalid session");state={...structuredClone(seeded),...loaded,joinCode:"KLAAR-MAAN-ROBOT",pin:String(Math.floor(100000+Math.random()*900000)).replace(/(\d{3})(\d{3})/,"$1 $2"),paused:false};saveAndRender();notify("Klas hervat. De nieuwe klascode staat klaar.");}catch{notify("Dit klasbestand kan niet worden geopend.");}e.target.value="";});
function showFinishDialog(){const wrap=document.createElement("div");wrap.className="modal-backdrop";wrap.innerHTML=`<section class="modal" role="dialog" aria-modal="true" aria-labelledby="finish-title"><h2 id="finish-title">Hoe ging de opdracht?</h2><p class="subtitle">Kies het gezicht dat het beste bij jou past.</p><div class="range" role="group" aria-label="Geef aan hoe de opdracht ging"><button data-feel="😕" aria-pressed="false">😕</button><button data-feel="😐" aria-pressed="false">😐</button><button data-feel="🙂" aria-pressed="true">🙂</button></div><div class="modal-actions"><button class="button secondary" data-close>Terug</button><button class="button" data-submit-feeling>Verstuur</button></div></section>`;document.body.append(wrap);let feeling="🙂";wrap.addEventListener("click",event=>{const feel=event.target.closest("[data-feel]");if(feel){feeling=feel.dataset.feel;wrap.querySelectorAll("[data-feel]").forEach(b=>b.setAttribute("aria-pressed",String(b===feel)));}if(event.target.closest("[data-close]")||event.target===wrap){wrap.remove();return;}if(event.target.closest("[data-submit-feeling]")){const id=sessionStorage.getItem("klascode.student");state.students=state.students.map(s=>s.id===id?{...s,status:"Klaar",feeling}:s);persist();sessionStorage.removeItem("klascode.student");wrap.remove();render();notify("Je werk is ingeleverd. Bedankt!");}});}
render();
